# syntax=docker/dockerfile:1
FROM python:3.10-slim
RUN mkdir -p /root/A2rchi
WORKDIR /root/A2rchi

COPY requirements.txt requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . /root/A2rchi/
RUN pip install .

ENV PYTHONPATH=/root/A2rchi

CMD ["python", "-u", "a2rchi/bin/service_chat.py"]
