[project]
name = "a2rchi"
version = "0.1.0"
description = "An AI Augmented Research Chat Intelligence (A2rchi)"
requires-python = ">=3.7"
# sorted alphabetically by last name
authors = [
    {name="Julius Heitkoetter", email="juliush@mit.edu"},
    {name="Time Kraska", email="kraska@mit.edu"},
    {name="Ludovico Mori", email="mori25@mit.edu"},
    {name="Christoph Paus", email="paus@mit.edu"},
    {name="Matthew Russo", email="mdrusso@mit.edu"},
]
dependencies = [
    "pyyaml==6.0.1",
    "click==8.1.7",
    "jinja2==3.1.3",
    "requests==2.31.0",
]

[project.scripts]
a2rchi = "a2rchi.cli.cli_main:main"

[tool.setuptools.package-data]
a2rchi = ["templates/*", "templates/grafana/*"]

[tool.setuptools.packages.find]
where = ["."]

[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project.urls]
"Homepage" = "https://github.com/mit-submit/A2rchi"
