FROM python:3.10.13-slim-bullseye

WORKDIR /app

RUN apt-get update --fix-missing && \
    apt-get install -y --no-install-recommends build-essential python3-dev g++ cmake && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN g++ --version  # Verifica que la versión sea >= 4.8

COPY requirements.txt .

ENV CXXFLAGS="-std=c++11"
ENV HNSWLIB_NO_NATIVE=1


COPY a2rchi a2rchi

RUN ls -lR a2rchi

RUN pip install --upgrade pip setuptools wheel && \
    pip install hnswlib && \
    pip install --no-cache-dir -r requirements.txt



EXPOSE 7861

CMD ["python", "-m", "a2rchi.cli.cli_main"]


